### ISSUE TITLE
Court: add documentation for the auto reveal service

### ISSUE THREAD

**Issue by sohkai** [aragon/help#28]
Add link in Court Dashboard: https://github.com/aragon/court-dashboard/blob/development/src/components/Disputes/panels/CommitPanel.js#L251

Aragon One runs an automated service to help people reveal their votes.

**Comment by john-light** [comment]
@sohkai I believe it's already documented:

https://help.aragon.org/article/43-dispute-lifecycle#onetime

> Enable Court Auto-reveal service is a convenient option available if you want your vote to be revealed automatically during the next phase. Otherwise, a manual action will be necessary.

https://help.aragon.org/article/43-dispute-lifecycle#vote-reveal

> If you enabled the Auto-reveal service, there is no action required from you at this stage. Otherwise, simply click on the Reveal your vote button. Your one-time code shouldn't be necessary unless a problem occurred within the court, but if it is needed, you'll be prompted to retrieve it from the safe place you stored it and enter it into the juror app.

**Comment by sohkai** [comment]
Thanks! Had a quick scan through, but didn't see it!
