### ISSUE TITLE
Add documention for missing permissions to User Guide

### ISSUE THREAD

**Issue by john-light** [aragon/help#3]
Token Manager
~- Burn Tokens~
~- Issue Tokens~

Finance
~- Change period duration~
~- Change budgets~
~- Manage payments~

**Comment by john-light** [comment]
@sohkai what does the `Manage payments` permission in the Finance app do?

**Comment by sohkai** [comment]
@john-light Technically, you can create recurring, scheduled payments in Finance. `Manage payments` would allow you to manage those payments (disable or re-activate).

**Comment by john-light** [comment]
@sohkai so does `Manage payments` allow the user to do any of the other actions on the Finance app? Or how is it different from these other permissions?

![Screenshot_2020-03-25 Aragon](https://user-images.githubusercontent.com/9424721/77552808-622ed500-6e8a-11ea-98d1-b7e356eae342.png)

**Comment by sohkai** [comment]
Different; those all give you access to different functionality from each other.

Only manage and execute payments are related, but cannot do the other (e.g. manage can turn on / off, execute can actually execute).
